cart/urls.py
from django.urls import path,include
from . import views
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name="cart"),
    path('add/', views.add_to_cart, name="add_to_cart"),
    path('remove/', views.remove_from_cart, name="rem_from_cart"),
    path('update/', views.update_cart, name="update_cart"),
    path('empty-cart/', views.empty_cart, name='empty_cart'),   
    path('checkout/', views.checkout_page, name='checkout'),

    # Paypal Urls for payments
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('payment-cancel/', views.payment_cancel, name='payment_cancel'),
]

core/urls.py
from django.urls import path, include
from core.views import index
from .views import *

app_name = 'core'

urlpatterns = [
    path('', LandingPageView.as_view(), name='landing'),  # Landing page view
    path("index/", index, name='index'),  # Make sure to use the view function, not a string
    path("products/", product_list_view, name='product-list'),  # Make sure to use the view function, not a string
    path('category/<str:category_name>/', products_by_category, name='products_by_category'),
    path('orders/', view_orders, name="view_orders" ),
    path('details/<int:product_id>/', view_details, name='view_details'),
]

speedesales/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),  # This line includes your core app's URLs
    path('user/', include('userauths.urls')), # This line includes your authusers app's URLs
    path('cart/', include('cart.urls')),  # This line includes your cart app's URLs

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths.views import registration_page, login_page, logout_page

app_name = 'userauths'

urlpatterns = [
    path("sign-up/", registration_page, name='registration_page'),  # Make sure to use the view function, not a string
    path("sign-in/", login_page, name='login_page'),
    path("sign-out/", logout_page, name='sign-out'),
]

templates/components/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Speed-E-Sales</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/icon.png' %}"/>
    <!-- Halfmoon CSS -->
    <link href="https://cdn.jsdelivr.net/npm/halfmoon@2.0.2/css/halfmoon.min.css" rel="stylesheet" integrity="sha256-RjeFzczeuZHCyS+Gvz+kleETzBF/o84ZRHukze/yv6o=" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
</head>
<!-- Set the background image -->
<style>
    body {
      background-image: url("{% static 'images/banner_cart.jpg' %}");
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }
</style>
<body class="d-flex flex-column min-vh-100">
    <!-- Bootstrap JS bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha256-CDOy6cOibCWEdsRiZuaHf8dSGGJRYuBGC+mjoJimHGw=" crossorigin="anonymous"></script>
    <!-- Custom JS page -->
    <script type = "text/javascript" src="{% static 'scripts/functions.js' %}"></script>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    
    <!--Navbar-->
    {% include 'components/navbar.html'%}

    <!-- Message Wrapper -->
    <div class="message-wrapper">
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" style="position: fixed; bottom: 30px; right: 20px; z-index: 10;">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    
    <!--Unique Page HTML-->
    <main class="container-fluid flex-grow-1 p-2 bg-black bg-opacity-50">
    {% block content %}
    {% endblock %}
    </main>

    
    <!--Website Footer-->
    {% include 'components/footer.html'%}

</body>

    <!-- Auto-collapse of messages -->
    <script>
        setTimeout(() => {
            const messageWrapper = document.querySelector('.message-wrapper');
            const messages = document.querySelectorAll('.messages .alert');
            messages.forEach((message) => {
                message.style.transition = "opacity 1s";
                message.style.opacity = "0";
                setTimeout(() => message.remove(), 1000);
            });
            setTimeout(() => messageWrapper.classList.add('empty'), 1000);
        }, 5000);
    </script>
</html>

templates/components/category_carousel.html
{% load static %}
<!--Category Carousel Showing all product types-->
<div id="carousel-products" class="carousel slide mt-3 ps-5 pe-5" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'images/banner_food.jpg' %}" class="d-block w-100 rounded" alt="First slide">
            <a href="{% url 'core:products_by_category' 'Food' %}">
                <button type="button" class="btn btn-default text-bg-info text-white position-absolute"
                style="bottom:3rem; right: 10rem; left: 10rem; ">
                    <b>Shop Food</b>
                </button>
            </a>
        </div>
        <div class="carousel-item">
            <img src="{% static 'images/banner_clothes.jpg' %}" class="d-block w-100 rounded" alt="Second slide">
            <a href="{% url 'core:products_by_category' 'Clothing' %}">
                <button type="button" class="btn btn-default text-bg-info text-white position-absolute"
                style="bottom:3rem; right: 10rem; left: 10rem; ">
                    <b>Shop Clothing</b>
                </button>
            </a>
        </div>
        <div class="carousel-item">
            <img src="{% static 'images/banner_tech.jpg' %}" class="d-block w-100 rounded" alt="Third slide">
            <a href="{% url 'core:products_by_category' 'Technology' %}">
                <button type="button" class="btn btn-default text-bg-info text-white position-absolute"
                style="bottom:3rem; right: 10rem; left: 10rem; ">
                    <b>Shop Technology</b>
                </button>
            </a>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carousel-products" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carousel-products" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

templates/components/footer.html
    <!-- Website Footer-->
    <footer class="footer text-white text-bg-info text-center py-2">
        Thanks for visiting our shop for Advanced Database Management Systems!
    </footer>

templates/components/navbar.html
<!--Navbar-->
<!--Use the Django include tag to place this in all pages-->
<nav class="navbar navbar-expand-lg text-bg-info rounded-bottom" style="background-color: var(--bs-content-bg); border-bottom: var(--bs-border-width) solid var(--bs-content-border-color);">
    <div class="container-fluid">
        <!--LOGO-->
        <a class="navbar-brand" href="{% url 'core:index' %}">
            <h1 class="text-white">
                $peed-E-$ales
            </h1>
        </a>
        <!--Toggle Navbar (for small screens)-->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-theme="dark" data-bs-target="#navbar-collapse-1" aria-controls="navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!--Collapsable Elements-->
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!--Profile Options-->
                <h5>
                    {%if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {% if user.is_authenticated %}
                                Hi, {{ user.username }}
                            {% else %}
                                Profile
                            {% endif %}                       </a>
                            <ul class="dropdown-menu mt-lg-2 text-bg-warning rounded-top-0">
                                    <li><a class="dropdown-item" href="{% url 'core:view_orders' %}">Orders</a></li>
                                    <!--<li><a class="dropdown-item" href="#">Settings</a></li>-->
                                    <li><a class="dropdown-item" href="{% url 'userauths:sign-out' %}">Log Out</a></li>
                                </ul>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'userauths:login_page' %}">Log In</a>
                        </li>                            
                    {% endif %}
                </h5>
                <h5>
                <!-- Cart -->
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'cart:cart' %}">Cart <span class="count" id="cart-count">({{ cart.get_qty }})</span></a>                    
                </li>                
                </h5>
                <!--Product Categories -->
                <h5>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Products
                        </a>
                        <ul class="dropdown-menu mt-lg-2 text-bg-warning rounded-top-0">
                            <li><a class="dropdown-item" href="{% url 'core:products_by_category' 'Clothing' %}">Clothing</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:products_by_category' 'Technology' %}">Technology</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:products_by_category' 'Food' %}">Food</a></li>
                        </ul>
                    </li>
                </h5>
            </ul>
            <!--Search Bar-->
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search items" aria-label="Search">
                <button class="btn btn-primary text-bg-warning" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>